### ISSUE TITLE
Automatically generate projects list in README

### ISSUE THREAD

**Issue by wotnak** [wotnak/farmos-community-projects#3]
JSON data format is easy to consume programmatically, but it would be nice to also display the projects list in a more human friendly format, for example in README.md.

Manually keeping README.md in sync with changes in the `projects.json` would be probably hard, so it should be automated.

The preferred way to achieve this would be to configure GitHub actions so on every push to main branch readme would be automatically updated to reflect changes introduced in the `projects.json` file.

**Comment by paul121** [comment]
Another approach could be to publish these to a simple GitHub pages site. They could be published in simple markdown and have the ability to add additional styling over time.

It's a step further but I would really love to see this used to generate a list of community/contrib modules on farmOS.org, too!

**Comment by wotnak** [comment]
> It's a step further but I would really love to see this used to generate a list of community/contrib modules on farmOS.org, too!

https://github.com/farmOS/farmOS.org/compare/main...wotnak:farmOS.org:community-projects
https://wondrous-tartufo-9df267.netlify.app/community/projects

**Comment by paul121** [comment]
Amazing! I mean.. I think that covers all the basics and would be useful as is. Would you like to open a PR so we could start discussing this possibility?

**Comment by wotnak** [comment]
Created the pr: https://github.com/farmOS/farmOS.org/pull/67
I'll close this issue now. If the list will be included on the main site, there's no need to also generate it into readme. It will be enough to include a link to the farmOS.org page in the readme when the list is added to it.
